apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "watchman.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "watchman.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "watchman.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "watchman.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "watchman.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:v{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -http.addr=:{{ .Values.service.http.port }}
            - -admin.addr=:{{ .Values.service.admin.port }}
          env: # TODO(adam): mysql env variables
            - name: HTTPS_CERT_FILE
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-tls-cert
                  key: cert
            - name: HTTPS_KEY_FILE
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-tls-cert
                  key: key
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9090
              name: admin
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            httpGet:
              path: /ping
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
