apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls-cert
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  cert: {{ .Files.Get "ach.crt" | b64enc | quote }}
  key: {{ .Files.Get "ach.key" | b64enc | quote }}
