apiVersion: v1
kind: Service
metadata:
  name: {{ include "ach.fullname" . }}
  labels:
    {{- include "ach.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: 8080
      protocol: TCP
      name: http
    - port: {{ .Values.service.admin.port }}
      targetPort: 9090
      protocol: TCP
      name: metrics
  selector:
    {{- include "ach.selectorLabels" . | nindent 4 }}
