apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paygate.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "paygate.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "paygate.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "paygate.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "paygate.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            # TODO(adam): We need to mount the config file / Secret
            - -config=/opt/moov/paygate/conf/config.yaml
          ports:
            - name: http
              containerPort: {{ .Values.service.http.port }}
              protocol: TCP
            - name: admin
              containerPort: {{ .Values.service.admin.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /live
              port: admin
          readinessProbe:
            httpGet:
              path: /live
              port: admin
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
